spring:
  datasource:
    # Persistente H2-Datenbank (Dateimodus) im Projektordner
    url: jdbc:h2:file:./data/ghostnetdb;AUTO_SERVER=TRUE;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    # Offen lassen, damit LAZY-Relations in Views geladen werden können
    open-in-view: true
    properties:
      hibernate.format_sql: true
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
server:
  port: 8080
  error:
    include-message: always
